name: Fail most of the time

on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Always finish
        run: exit 0;
      - name: Fail first three
        run: |
          if [[ ${{ github.run_attempt }} -gt 3 ]]; then echo "Yay, ${{ github.run_attempt }} > 3" && exit 0; else echo "Nay, ${{ github.run_attempt }} <= 3" && exit 1; fi;
      - name: Fail first six
        run: |
          if [[ ${{ github.run_attempt }} -gt 6 ]]; then echo "Yay, ${{ github.run_attempt }} > 6" && exit 0; else echo "Nay, ${{ github.run_attempt }} <= 6" && exit 1; fi;
