name: Run until works

on: [ push ]

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: ensure build works
        run: |
          gh workflow run fail-most-of-the-time.yaml;
          printf "RUNID=%q\n" "$(gh run list --workflow=fail-most-of-the-time.yaml"--limit 1 --json databaseId --jq '.[0].databaseId')" >> $GITHUB_ENV
          echo "Workflow id is ${{ env.RUNID }}"
          while ! gh run watch "${{ env.RUNID }} --exit-status; do gh run rerun "${{ env.RUNID }}" $(gh run list --workflow=fail-most-of-the-time.yaml --limit 1 --json databaseId --jq '.[0].databaseId')" --failed; done;'
        env:
          GH_TOKEN: ${{ github.token }}
