name: Run until works

on: [ push ]
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Trigger build
        run: |
          gh workflow run fail-most-of-the-time.yaml;
          printf "RUNID=%q\n" "$(gh run list --workflow=fail-most-of-the-time.yaml --limit 1 --json databaseId --jq '.[0].databaseId')" >> $GITHUB_ENV
      - name: Retry failed until works
        run: |
          while ! gh run watch "${{ env.RUNID }}" --exit-status; do gh run rerun "${{ env.RUNID }}" --failed; done;
