name: trigger one

on: [ push ]
permissions: write-all
jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: dl
        run: |
          gh release download --repo "teragrep/rlp_10" --pattern "*.rpm" --dir "test1" "1.0.0";
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Create one
        uses: StrongestNumber9/dfg_01@merged_release
        with:
          from_repository: teragrep/rlp_10
          from_version: 1.0.0
          to_repository: StrongestNumber9/pkg_01
          token: ${{ secrets.PAT_TOKEN }}
          files: test1/*
          max_attempts: 5
