name: Trigger three

on: [ push ]
permissions: write-all
jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create three
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          from_repository: teragrep/bos_01
          from_version: 2.0.0
          to_repository: StrongestNumber9/pkg_01
          token: ${{ secrets.PAT_TOKEN }}
          max_attempts: 5
