name: Trigger create repo

on: [ push ]

jobs:
  create-repo:
    permissions:
      actions: write
      contents: write
    uses: StrongestNumber9/repodemo/.github/workflows/create_repo.yaml@main
    with:
      component_path: teragrep/pth_10
      component_version: 10.4.0

  retry_failed_jobs:
    runs-on: ubuntu-latest
    if: failure() && fromJSON(github.run_attempt) < 3
    steps:
      - name: Retry failed jobs
        run: gh run rerun "${{ github.run_id }}" --failed
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
