name: Trigger create repo

on: [ push ]

jobs:
  create_repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Create repo
        uses: StrongestNumber9/dfg_01@main
        with:
          repository: teragrep/jla_02
          version: 1.5.0
