name: Trigger three

on: [ push ]
permissions: write-all
jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: dl
        run: |
          gh release download --repo "teragrep/pth_10" --pattern "*.rpm" --dir "test2" "11.0.1";
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Create three
        uses: StrongestNumber9/dfg_01@use_personal_token
        with:
          from_repository: teragrep/pth_10
          from_version: 11.0.1
          to_repository: StrongestNumber9/pkg_01
          token: ${{ github.token }}
          files: test2/*.rpm
          max_attempts: 5
