name: Trigger create repo pth_10 v 10.4.1

on: [ push ]
permissions: write-all
jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create pth_10 repo 10.4.1
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          from_repository: pth_10
          from_version: 10.4.1
          to_repository: StrongestNumber9/pkg_01
          token: ${{ secrets.PAT_TOKEN }}
          max_retries: 1
