name: Trigger create repo

on: [ push ]

jobs:
  create_repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create repo
        uses: ./.github/actions/create_repo
        with:
          component_path: teragrep/pth_10
          component_version: 10.4.0
