name: Trigger two

on: [ push ]
permissions: write-all
jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: dl
        run: |
          gh release download --repo teragrep/bos_01 --pattern "*.rpm" --dir "test3" 2.1.0;
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Create two
        uses: StrongestNumber9/dfg_01@use_deploy_key
        with:
          from_repository: teragrep/bos_01
          from_version: 2.1.0
          to_repository: StrongestNumber9/pkg_01
          deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          files: test3/*.rpm
          max_attempts: 5
