name: Trigger create repo

on: [ release ]

jobs:
  create_repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Create repo 10.4.1
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          repository: teragrep/pth_10
          version: 10.4.1
          to_path: new_repo
      - name: Create repo 10.4.0
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          repository: teragrep/pth_10
          version: 10.4.0
          to_path: new_repo
      - name: Create repo 10.3.4
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          repository: teragrep/pth_10
          version: 10.3.4
          to_path: new_repo
