name: Trigger create repo pth_07 v 8.3.0

on: [ push ]
permissions: write-all
jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create pth_07 repo 8.3.0
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          from_repository: teragrep/pth_07
          from_version: 8.3.0
          to_repository: StrongestNumber9/pkg_01
          token: ${{ secrets.PAT_TOKEN }}
          max_retries: 5
