name: Trigger create repo

on: [ push ]
jobs:
  create_repo:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create pth_10 repo 10.4.1
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          from_repository: pth_10
          from_version: 10.4.1
          to_repository: StrongestNumber9/pkg_01
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create pth_10 repo 10.4.0
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          from_repository: pth_10
          from_version: 10.4.0
          to_repository: StrongestNumber9/pkg_01
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create jla_02 repo 1.5.0
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          from_repository: jla_02
          from_version: 1.5.0
          to_repository: StrongestNumber9/pkg_01
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create jla_02 repo 1.4.0
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          from_repository: jla_02
          from_version: 1.4.0
          to_repository: StrongestNumber9/pkg_01
        env:
          GH_TOKEN: ${{ github.token }}
