name: Trigger create repo jla_02 v 1.5.0

on: [ push ]
permissions: write-all
jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create jla_02 repo 1.5.0
        uses: StrongestNumber9/dfg_01@initial_release
        with:
          from_repository: teragrep/jla_02
          from_version: 1.5.0
          to_repository: StrongestNumber9/pkg_01
          token: ${{ secrets.PAT_TOKEN }}
          max_retries: 1
