name: Trigger create repo

on: [ push ]

jobs:
  create_repo:
    permissions:
      contents: write
    uses: StrongestNumber9/repodemo/.github/workflows/create_repo.yaml@main
    with:
      component_path: teragrep/pth_10
      component_version: 10.4.0
