name: Trigger create repo

on: [ push ]

jobs:
  create_repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Create repo
        uses: StrongestNumber9/repodemo/.github/actions/create_repo@main
        with:
          component_path: teragrep/pth_10
          component_version: 10.4.0
