name: Trigger two

on: [ push ]
permissions: write-all
jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: dl
        runs: |
          gh release download --repo teragrep/bos_01 --pattern "*.rpm" --dir "test3" 2.1.0;
      - name: Create two
        uses: StrongestNumber9/dfg_01@merged_release
        with:
          from_repository: teragrep/bos_01
          from_version: 2.1.0
          to_repository: StrongestNumber9/pkg_01
          token: ${{ secrets.PAT_TOKEN }}
          max_attempts: 5
