name: Trigger create repo

on: [ push ]

jobs:
  create_repo:
    permissions:
      actions: write
      contents: write
    uses: StrongestNumber9/repodemo/.github/workflows/create_repo.yaml@main
    with:
      component_path: teragrep/pth_10
      component_version: 10.4.0

  retry_failed_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Retry failed jobs
        run: for i in {1..5}; do echo "Run ${i}";  gh run rerun "${{ github.run_id }}" --failed && break; done;
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
