name: Trigger create repo

on: [ push ]

jobs:
  create_repo:
    permissions:
      contents: write
    uses: StrongestNumber9/repodemo/.github/workflows/create_repo.yaml@main
    with:
      component_path: teragrep/pth_10
      component_version: 10.4.0

  retry_failed_jobs:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [ create_repo ]
    steps:
      - name: Retry failed jobs
        run: for jobid in $(gh run view "${{ github.run_id }}" --json jobs --jq '.jobs[] | select(.conclusion=="failure").databaseId'); do gh run rerun --job "${jobid}"; done;
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
